"use client";

export const colors = {
  primary: '#2ecc71',
  secondary: '#2c3e50',
  textSecondary: '#7f8c8d',
  background: '#ffffff',
  border: '#ddd',
};

export const sharedStyles = {
  pageWrapper: {
    display: "flex",
    height: "100vh",
    width: "100vw",
    overflow: "hidden",
  },
  leftColumn: {
    flex: "0 0 28%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: "6%",
    backgroundColor: colors.background,
    zIndex: 2,
  },
  logoStyle: {
    fontFamily: "'Lexend', sans-serif",
    fontSize: "3rem",
    color: colors.secondary,
    marginBottom: "5px",
    fontWeight: "700"
  },
  subtitleStyle: {
    fontFamily: "'Lexend', sans-serif",
    color: "#7f8c8d",
    marginBottom: "30px",
  },
  formGroup: {
    marginBottom: "20px",
    display: "flex",
    flexDirection: "column",
    width: "325px",
  },
  labelStyle: {
    fontFamily: "'Lexend', sans-serif",
    fontSize: "14px",
    fontWeight: "600",
    marginBottom: "8px",
    color: "#34495e",
  },
  inputStyle: {
    fontFamily: "'Lexend', sans-serif",
    padding: "12px",
    width: "100%", 
    borderRadius: "6px",
    color: "#2c3e50",
    border: "1px solid #ddd",
    backgroundColor: "#f9f9f9",
    boxSizing: "border-box",
  },
  rightColumn: {
    flex: "1",
    backgroundImage: "url('/background.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundColor: "#16171d",
  },
  buttonStyle: (bgColor = colors.primary, custom = {}) => ({
    padding: custom.padding || "12px 30px",
    width: custom.width || "325px",
    backgroundColor: bgColor,
    color: "white",
    border: "none",
    borderRadius: custom.borderRadius || "6px",
    cursor: "pointer",
    fontFamily: "'Lexend', sans-serif",
    fontWeight: "bold",
    fontSize: custom.fontSize || "16px",
    marginBottom: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  }),
  secondaryBtnStyle: {
    padding: "12px",
    width: "325px",
    borderRadius: "6px",
    border: "1px solid #ddd",
    backgroundColor: "white",
    color: "#2c3e50",
    cursor: "pointer",
    fontFamily: "'Lexend', sans-serif",
    fontSize: "14px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "500",
    boxSizing: "border-box",
  },
  dashboardWrapper: {
    backgroundColor: '#f4f7f6',
    minHeight: '100vh',
    width: '100vw',
},
  onboardingWrapper: {
    backgroundColor: '#f4f7f6',
    minHeight: '100vh',
    width: '100vw',
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: "200px",
    overflow: 'hidden',
  }
};